import About from '@/components/About'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import Main from '@/components/Main'
import Navbar from '@/components/Navbar'
import Projects from '@/components/Projects'
import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Vaibhav | Front-end Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
      <Main />
      <About />
      <Projects />
      <Contact />
      <Footer />

    </div>
  )
}
